//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 11:16:59 AM CST 
//


package org.mesa.xml.kpi_ml4j;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConfirmBODType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfirmBODType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ApplicationArea" type="{http://www.mesa.org/xml/KPI-ML-V01}TransApplicationAreaType"/>
 *         &lt;element name="DataArea">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Confirm" type="{http://www.mesa.org/xml/KPI-ML-V01}TransConfirmType"/>
 *                   &lt;element name="BOD" type="{http://www.mesa.org/xml/KPI-ML-V01}BODType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfirmBODType", propOrder = {
    "applicationArea",
    "dataArea"
})
public class ConfirmBODType {

    @XmlElement(name = "ApplicationArea", required = true)
    protected TransApplicationAreaType applicationArea;
    @XmlElement(name = "DataArea", required = true)
    protected ConfirmBODType.DataArea dataArea;

    /**
     * Gets the value of the applicationArea property.
     * 
     * @return
     *     possible object is
     *     {@link TransApplicationAreaType }
     *     
     */
    public TransApplicationAreaType getApplicationArea() {
        return applicationArea;
    }

    /**
     * Sets the value of the applicationArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransApplicationAreaType }
     *     
     */
    public void setApplicationArea(TransApplicationAreaType value) {
        this.applicationArea = value;
    }

    /**
     * Gets the value of the dataArea property.
     * 
     * @return
     *     possible object is
     *     {@link ConfirmBODType.DataArea }
     *     
     */
    public ConfirmBODType.DataArea getDataArea() {
        return dataArea;
    }

    /**
     * Sets the value of the dataArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfirmBODType.DataArea }
     *     
     */
    public void setDataArea(ConfirmBODType.DataArea value) {
        this.dataArea = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Confirm" type="{http://www.mesa.org/xml/KPI-ML-V01}TransConfirmType"/>
     *         &lt;element name="BOD" type="{http://www.mesa.org/xml/KPI-ML-V01}BODType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "confirm",
        "bod"
    })
    public static class DataArea {

        @XmlElement(name = "Confirm", required = true)
        protected TransConfirmType confirm;
        @XmlElement(name = "BOD", required = true)
        protected List<BODType> bod;

        /**
         * Gets the value of the confirm property.
         * 
         * @return
         *     possible object is
         *     {@link TransConfirmType }
         *     
         */
        public TransConfirmType getConfirm() {
            return confirm;
        }

        /**
         * Sets the value of the confirm property.
         * 
         * @param value
         *     allowed object is
         *     {@link TransConfirmType }
         *     
         */
        public void setConfirm(TransConfirmType value) {
            this.confirm = value;
        }

        /**
         * Gets the value of the bod property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bod property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBOD().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BODType }
         * 
         * 
         */
        public List<BODType> getBOD() {
            if (bod == null) {
                bod = new ArrayList<BODType>();
            }
            return this.bod;
        }

    }

}
