//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 11:16:59 AM CST 
//


package org.mesa.xml.kpi_ml4j;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KPIDefinitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KPIDefinitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.mesa.org/xml/KPI-ML-V01}IdentifierType"/>
 *         &lt;element name="Description" type="{http://www.mesa.org/xml/KPI-ML-V01}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.mesa.org/xml/KPI-ML-V01}IdentifierType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Scope" type="{http://www.mesa.org/xml/KPI-ML-V01}ScopeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Formula" type="{http://www.mesa.org/xml/KPI-ML-V01}TextType" minOccurs="0"/>
 *         &lt;element name="UnitOfMeasure" type="{http://www.mesa.org/xml/KPI-ML-V01}CodeType" minOccurs="0"/>
 *         &lt;element name="Range" type="{http://www.mesa.org/xml/KPI-ML-V01}RangeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Trend" type="{http://www.mesa.org/xml/KPI-ML-V01}TrendType" minOccurs="0"/>
 *         &lt;element name="Timing" type="{http://www.mesa.org/xml/KPI-ML-V01}TimingType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TimeRange" type="{http://www.mesa.org/xml/KPI-ML-V01}TimeRangeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Audience" type="{http://www.mesa.org/xml/KPI-ML-V01}AudianceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ProductionMethodology" type="{http://www.mesa.org/xml/KPI-ML-V01}ProductionMethodologyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EffectModel" type="{http://www.mesa.org/xml/KPI-ML-V01}EffectModelType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Notes" type="{http://www.mesa.org/xml/KPI-ML-V01}TextType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UsesKPIDefinitionID" type="{http://www.mesa.org/xml/KPI-ML-V01}IdentifierType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="KPIInstanceID" type="{http://www.mesa.org/xml/KPI-ML-V01}IdentifierType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Property" type="{http://www.mesa.org/xml/KPI-ML-V01}PropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/KPI-ML-V01-Extensions}KPIDefinition" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KPIDefinitionType", propOrder = {
    "id",
    "description",
    "name",
    "scope",
    "formula",
    "unitOfMeasure",
    "range",
    "trend",
    "timing",
    "timeRange",
    "audience",
    "productionMethodology",
    "effectModel",
    "notes",
    "usesKPIDefinitionID",
    "kpiInstanceID",
    "property"
})
public class KPIDefinitionType {

    @XmlElement(name = "ID", required = true, nillable = true)
    protected IdentifierType id;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "Name")
    protected List<IdentifierType> name;
    @XmlElement(name = "Scope")
    protected List<ScopeType> scope;
    @XmlElement(name = "Formula")
    protected TextType formula;
    @XmlElement(name = "UnitOfMeasure")
    protected CodeType unitOfMeasure;
    @XmlElement(name = "Range")
    protected List<RangeType> range;
    @XmlElement(name = "Trend")
    protected TrendType trend;
    @XmlElement(name = "Timing")
    protected List<TimingType> timing;
    @XmlElement(name = "TimeRange")
    protected List<TimeRangeType> timeRange;
    @XmlElement(name = "Audience")
    protected List<AudianceType> audience;
    @XmlElement(name = "ProductionMethodology")
    protected List<ProductionMethodologyType> productionMethodology;
    @XmlElement(name = "EffectModel")
    protected List<EffectModelType> effectModel;
    @XmlElement(name = "Notes")
    protected List<TextType> notes;
    @XmlElement(name = "UsesKPIDefinitionID")
    protected List<IdentifierType> usesKPIDefinitionID;
    @XmlElement(name = "KPIInstanceID")
    protected List<IdentifierType> kpiInstanceID;
    @XmlElement(name = "Property")
    protected List<PropertyType> property;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setID(IdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * 
     * 
     */
    public List<IdentifierType> getName() {
        if (name == null) {
            name = new ArrayList<IdentifierType>();
        }
        return this.name;
    }

    /**
     * Gets the value of the scope property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scope property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScope().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScopeType }
     * 
     * 
     */
    public List<ScopeType> getScope() {
        if (scope == null) {
            scope = new ArrayList<ScopeType>();
        }
        return this.scope;
    }

    /**
     * Gets the value of the formula property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getFormula() {
        return formula;
    }

    /**
     * Sets the value of the formula property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setFormula(TextType value) {
        this.formula = value;
    }

    /**
     * Gets the value of the unitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getUnitOfMeasure() {
        return unitOfMeasure;
    }

    /**
     * Sets the value of the unitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setUnitOfMeasure(CodeType value) {
        this.unitOfMeasure = value;
    }

    /**
     * Gets the value of the range property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the range property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RangeType }
     * 
     * 
     */
    public List<RangeType> getRange() {
        if (range == null) {
            range = new ArrayList<RangeType>();
        }
        return this.range;
    }

    /**
     * Gets the value of the trend property.
     * 
     * @return
     *     possible object is
     *     {@link TrendType }
     *     
     */
    public TrendType getTrend() {
        return trend;
    }

    /**
     * Sets the value of the trend property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrendType }
     *     
     */
    public void setTrend(TrendType value) {
        this.trend = value;
    }

    /**
     * Gets the value of the timing property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timing property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTiming().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimingType }
     * 
     * 
     */
    public List<TimingType> getTiming() {
        if (timing == null) {
            timing = new ArrayList<TimingType>();
        }
        return this.timing;
    }

    /**
     * Gets the value of the timeRange property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timeRange property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimeRange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeRangeType }
     * 
     * 
     */
    public List<TimeRangeType> getTimeRange() {
        if (timeRange == null) {
            timeRange = new ArrayList<TimeRangeType>();
        }
        return this.timeRange;
    }

    /**
     * Gets the value of the audience property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the audience property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAudience().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AudianceType }
     * 
     * 
     */
    public List<AudianceType> getAudience() {
        if (audience == null) {
            audience = new ArrayList<AudianceType>();
        }
        return this.audience;
    }

    /**
     * Gets the value of the productionMethodology property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productionMethodology property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductionMethodology().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductionMethodologyType }
     * 
     * 
     */
    public List<ProductionMethodologyType> getProductionMethodology() {
        if (productionMethodology == null) {
            productionMethodology = new ArrayList<ProductionMethodologyType>();
        }
        return this.productionMethodology;
    }

    /**
     * Gets the value of the effectModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the effectModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEffectModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EffectModelType }
     * 
     * 
     */
    public List<EffectModelType> getEffectModel() {
        if (effectModel == null) {
            effectModel = new ArrayList<EffectModelType>();
        }
        return this.effectModel;
    }

    /**
     * Gets the value of the notes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getNotes() {
        if (notes == null) {
            notes = new ArrayList<TextType>();
        }
        return this.notes;
    }

    /**
     * Gets the value of the usesKPIDefinitionID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usesKPIDefinitionID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsesKPIDefinitionID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * 
     * 
     */
    public List<IdentifierType> getUsesKPIDefinitionID() {
        if (usesKPIDefinitionID == null) {
            usesKPIDefinitionID = new ArrayList<IdentifierType>();
        }
        return this.usesKPIDefinitionID;
    }

    /**
     * Gets the value of the kpiInstanceID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kpiInstanceID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKPIInstanceID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * 
     * 
     */
    public List<IdentifierType> getKPIInstanceID() {
        if (kpiInstanceID == null) {
            kpiInstanceID = new ArrayList<IdentifierType>();
        }
        return this.kpiInstanceID;
    }

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyType }
     * 
     * 
     */
    public List<PropertyType> getProperty() {
        if (property == null) {
            property = new ArrayList<PropertyType>();
        }
        return this.property;
    }

}
