//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 11:16:59 AM CST 
//


package org.mesa.xml.kpi_ml4j;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mesa.xml.kpi_ml4j package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetKPIDefinition_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "GetKPIDefinition");
    private final static QName _ChangeKPIInstance_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "ChangeKPIInstance");
    private final static QName _RespondKPIValue_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "RespondKPIValue");
    private final static QName _ShowKPIInstance_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "ShowKPIInstance");
    private final static QName _AcknowledgeKPIValue_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "AcknowledgeKPIValue");
    private final static QName _ShowKPIDefinition_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "ShowKPIDefinition");
    private final static QName _ConfirmBOD_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "ConfirmBOD");
    private final static QName _ProcessKPIInstance_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "ProcessKPIInstance");
    private final static QName _RespondKPIInstance_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "RespondKPIInstance");
    private final static QName _KPIValue_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "KPIValue");
    private final static QName _ProcessKPIValue_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "ProcessKPIValue");
    private final static QName _RespondKPIDefinition_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "RespondKPIDefinition");
    private final static QName _AcknowledgeKPIDefinition_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "AcknowledgeKPIDefinition");
    private final static QName _ShowKPIValue_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "ShowKPIValue");
    private final static QName _AcknowledgeKPIInstance_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "AcknowledgeKPIInstance");
    private final static QName _GetKPIInstance_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "GetKPIInstance");
    private final static QName _SyncKPIDefinition_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "SyncKPIDefinition");
    private final static QName _SyncKPIValue_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "SyncKPIValue");
    private final static QName _CancelKPIValue_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "CancelKPIValue");
    private final static QName _ProcessKPIDefinition_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "ProcessKPIDefinition");
    private final static QName _ChangeKPIValue_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "ChangeKPIValue");
    private final static QName _KPIInstance_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "KPIInstance");
    private final static QName _KPIDefinition_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "KPIDefinition");
    private final static QName _GetKPIValue_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "GetKPIValue");
    private final static QName _CancelKPIInstance_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "CancelKPIInstance");
    private final static QName _CancelKPIDefinition_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "CancelKPIDefinition");
    private final static QName _ChangeKPIDefinition_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "ChangeKPIDefinition");
    private final static QName _SyncKPIInstance_QNAME = new QName("http://www.mesa.org/xml/KPI-ML-V01", "SyncKPIInstance");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mesa.xml.kpi_ml4j
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetKPIDefinitionType }
     * 
     */
    public GetKPIDefinitionType createGetKPIDefinitionType() {
        return new GetKPIDefinitionType();
    }

    /**
     * Create an instance of {@link ShowKPIInstanceType }
     * 
     */
    public ShowKPIInstanceType createShowKPIInstanceType() {
        return new ShowKPIInstanceType();
    }

    /**
     * Create an instance of {@link RespondKPIValueType }
     * 
     */
    public RespondKPIValueType createRespondKPIValueType() {
        return new RespondKPIValueType();
    }

    /**
     * Create an instance of {@link ChangeKPIInstanceType }
     * 
     */
    public ChangeKPIInstanceType createChangeKPIInstanceType() {
        return new ChangeKPIInstanceType();
    }

    /**
     * Create an instance of {@link ShowKPIDefinitionType }
     * 
     */
    public ShowKPIDefinitionType createShowKPIDefinitionType() {
        return new ShowKPIDefinitionType();
    }

    /**
     * Create an instance of {@link AcknowledgeKPIValueType }
     * 
     */
    public AcknowledgeKPIValueType createAcknowledgeKPIValueType() {
        return new AcknowledgeKPIValueType();
    }

    /**
     * Create an instance of {@link ConfirmBODType }
     * 
     */
    public ConfirmBODType createConfirmBODType() {
        return new ConfirmBODType();
    }

    /**
     * Create an instance of {@link RespondKPIInstanceType }
     * 
     */
    public RespondKPIInstanceType createRespondKPIInstanceType() {
        return new RespondKPIInstanceType();
    }

    /**
     * Create an instance of {@link ProcessKPIInstanceType }
     * 
     */
    public ProcessKPIInstanceType createProcessKPIInstanceType() {
        return new ProcessKPIInstanceType();
    }

    /**
     * Create an instance of {@link RespondKPIDefinitionType }
     * 
     */
    public RespondKPIDefinitionType createRespondKPIDefinitionType() {
        return new RespondKPIDefinitionType();
    }

    /**
     * Create an instance of {@link ProcessKPIValueType }
     * 
     */
    public ProcessKPIValueType createProcessKPIValueType() {
        return new ProcessKPIValueType();
    }

    /**
     * Create an instance of {@link AcknowledgeKPIDefinitionType }
     * 
     */
    public AcknowledgeKPIDefinitionType createAcknowledgeKPIDefinitionType() {
        return new AcknowledgeKPIDefinitionType();
    }

    /**
     * Create an instance of {@link ShowKPIValueType }
     * 
     */
    public ShowKPIValueType createShowKPIValueType() {
        return new ShowKPIValueType();
    }

    /**
     * Create an instance of {@link AcknowledgeKPIInstanceType }
     * 
     */
    public AcknowledgeKPIInstanceType createAcknowledgeKPIInstanceType() {
        return new AcknowledgeKPIInstanceType();
    }

    /**
     * Create an instance of {@link GetKPIInstanceType }
     * 
     */
    public GetKPIInstanceType createGetKPIInstanceType() {
        return new GetKPIInstanceType();
    }

    /**
     * Create an instance of {@link SyncKPIDefinitionType }
     * 
     */
    public SyncKPIDefinitionType createSyncKPIDefinitionType() {
        return new SyncKPIDefinitionType();
    }

    /**
     * Create an instance of {@link SyncKPIValueType }
     * 
     */
    public SyncKPIValueType createSyncKPIValueType() {
        return new SyncKPIValueType();
    }

    /**
     * Create an instance of {@link ProcessKPIDefinitionType }
     * 
     */
    public ProcessKPIDefinitionType createProcessKPIDefinitionType() {
        return new ProcessKPIDefinitionType();
    }

    /**
     * Create an instance of {@link CancelKPIValueType }
     * 
     */
    public CancelKPIValueType createCancelKPIValueType() {
        return new CancelKPIValueType();
    }

    /**
     * Create an instance of {@link ChangeKPIValueType }
     * 
     */
    public ChangeKPIValueType createChangeKPIValueType() {
        return new ChangeKPIValueType();
    }

    /**
     * Create an instance of {@link CancelKPIInstanceType }
     * 
     */
    public CancelKPIInstanceType createCancelKPIInstanceType() {
        return new CancelKPIInstanceType();
    }

    /**
     * Create an instance of {@link GetKPIValueType }
     * 
     */
    public GetKPIValueType createGetKPIValueType() {
        return new GetKPIValueType();
    }

    /**
     * Create an instance of {@link CancelKPIDefinitionType }
     * 
     */
    public CancelKPIDefinitionType createCancelKPIDefinitionType() {
        return new CancelKPIDefinitionType();
    }

    /**
     * Create an instance of {@link SyncKPIInstanceType }
     * 
     */
    public SyncKPIInstanceType createSyncKPIInstanceType() {
        return new SyncKPIInstanceType();
    }

    /**
     * Create an instance of {@link ChangeKPIDefinitionType }
     * 
     */
    public ChangeKPIDefinitionType createChangeKPIDefinitionType() {
        return new ChangeKPIDefinitionType();
    }

    /**
     * Create an instance of {@link KPIDefinitionType }
     * 
     */
    public KPIDefinitionType createKPIDefinitionType() {
        return new KPIDefinitionType();
    }

    /**
     * Create an instance of {@link KPIInstanceType }
     * 
     */
    public KPIInstanceType createKPIInstanceType() {
        return new KPIInstanceType();
    }

    /**
     * Create an instance of {@link KPIValueType }
     * 
     */
    public KPIValueType createKPIValueType() {
        return new KPIValueType();
    }

    /**
     * Create an instance of {@link TransChangeStatusType }
     * 
     */
    public TransChangeStatusType createTransChangeStatusType() {
        return new TransChangeStatusType();
    }

    /**
     * Create an instance of {@link TransResponseCriteriaType }
     * 
     */
    public TransResponseCriteriaType createTransResponseCriteriaType() {
        return new TransResponseCriteriaType();
    }

    /**
     * Create an instance of {@link ProductionMethodology1Type }
     * 
     */
    public ProductionMethodology1Type createProductionMethodology1Type() {
        return new ProductionMethodology1Type();
    }

    /**
     * Create an instance of {@link TransAcknowledgeType }
     * 
     */
    public TransAcknowledgeType createTransAcknowledgeType() {
        return new TransAcknowledgeType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link TransChangeType }
     * 
     */
    public TransChangeType createTransChangeType() {
        return new TransChangeType();
    }

    /**
     * Create an instance of {@link TransApplicationAreaType }
     * 
     */
    public TransApplicationAreaType createTransApplicationAreaType() {
        return new TransApplicationAreaType();
    }

    /**
     * Create an instance of {@link TransProcessType }
     * 
     */
    public TransProcessType createTransProcessType() {
        return new TransProcessType();
    }

    /**
     * Create an instance of {@link TransActionCriteriaType }
     * 
     */
    public TransActionCriteriaType createTransActionCriteriaType() {
        return new TransActionCriteriaType();
    }

    /**
     * Create an instance of {@link TransCancelType }
     * 
     */
    public TransCancelType createTransCancelType() {
        return new TransCancelType();
    }

    /**
     * Create an instance of {@link TransRespondType }
     * 
     */
    public TransRespondType createTransRespondType() {
        return new TransRespondType();
    }

    /**
     * Create an instance of {@link TransConfirmationCodeType }
     * 
     */
    public TransConfirmationCodeType createTransConfirmationCodeType() {
        return new TransConfirmationCodeType();
    }

    /**
     * Create an instance of {@link TransSyncType }
     * 
     */
    public TransSyncType createTransSyncType() {
        return new TransSyncType();
    }

    /**
     * Create an instance of {@link IdentifierType }
     * 
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link BinaryObjectType }
     * 
     */
    public BinaryObjectType createBinaryObjectType() {
        return new BinaryObjectType();
    }

    /**
     * Create an instance of {@link DateTimeType }
     * 
     */
    public DateTimeType createDateTimeType() {
        return new DateTimeType();
    }

    /**
     * Create an instance of {@link TransExpressionType }
     * 
     */
    public TransExpressionType createTransExpressionType() {
        return new TransExpressionType();
    }

    /**
     * Create an instance of {@link ResourceReferenceType }
     * 
     */
    public ResourceReferenceType createResourceReferenceType() {
        return new ResourceReferenceType();
    }

    /**
     * Create an instance of {@link TrendType }
     * 
     */
    public TrendType createTrendType() {
        return new TrendType();
    }

    /**
     * Create an instance of {@link TransReceiverType }
     * 
     */
    public TransReceiverType createTransReceiverType() {
        return new TransReceiverType();
    }

    /**
     * Create an instance of {@link TimingType }
     * 
     */
    public TimingType createTimingType() {
        return new TimingType();
    }

    /**
     * Create an instance of {@link MeasureType }
     * 
     */
    public MeasureType createMeasureType() {
        return new MeasureType();
    }

    /**
     * Create an instance of {@link TransExpression1Type }
     * 
     */
    public TransExpression1Type createTransExpression1Type() {
        return new TransExpression1Type();
    }

    /**
     * Create an instance of {@link TransShowType }
     * 
     */
    public TransShowType createTransShowType() {
        return new TransShowType();
    }

    /**
     * Create an instance of {@link TransUserAreaType }
     * 
     */
    public TransUserAreaType createTransUserAreaType() {
        return new TransUserAreaType();
    }

    /**
     * Create an instance of {@link AudianceType }
     * 
     */
    public AudianceType createAudianceType() {
        return new AudianceType();
    }

    /**
     * Create an instance of {@link TransGetType }
     * 
     */
    public TransGetType createTransGetType() {
        return new TransGetType();
    }

    /**
     * Create an instance of {@link EffectModelType }
     * 
     */
    public EffectModelType createEffectModelType() {
        return new EffectModelType();
    }

    /**
     * Create an instance of {@link RangeType }
     * 
     */
    public RangeType createRangeType() {
        return new RangeType();
    }

    /**
     * Create an instance of {@link Timing1Type }
     * 
     */
    public Timing1Type createTiming1Type() {
        return new Timing1Type();
    }

    /**
     * Create an instance of {@link TransConfirmType }
     * 
     */
    public TransConfirmType createTransConfirmType() {
        return new TransConfirmType();
    }

    /**
     * Create an instance of {@link TransStateChangeType }
     * 
     */
    public TransStateChangeType createTransStateChangeType() {
        return new TransStateChangeType();
    }

    /**
     * Create an instance of {@link ScopeType }
     * 
     */
    public ScopeType createScopeType() {
        return new ScopeType();
    }

    /**
     * Create an instance of {@link TransSignatureType }
     * 
     */
    public TransSignatureType createTransSignatureType() {
        return new TransSignatureType();
    }

    /**
     * Create an instance of {@link BODType }
     * 
     */
    public BODType createBODType() {
        return new BODType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link TimeRangeType }
     * 
     */
    public TimeRangeType createTimeRangeType() {
        return new TimeRangeType();
    }

    /**
     * Create an instance of {@link TransSenderType }
     * 
     */
    public TransSenderType createTransSenderType() {
        return new TransSenderType();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link Trend1Type }
     * 
     */
    public Trend1Type createTrend1Type() {
        return new Trend1Type();
    }

    /**
     * Create an instance of {@link ProductionMethodologyType }
     * 
     */
    public ProductionMethodologyType createProductionMethodologyType() {
        return new ProductionMethodologyType();
    }

    /**
     * Create an instance of {@link GetKPIDefinitionType.DataArea }
     * 
     */
    public GetKPIDefinitionType.DataArea createGetKPIDefinitionTypeDataArea() {
        return new GetKPIDefinitionType.DataArea();
    }

    /**
     * Create an instance of {@link ShowKPIInstanceType.DataArea }
     * 
     */
    public ShowKPIInstanceType.DataArea createShowKPIInstanceTypeDataArea() {
        return new ShowKPIInstanceType.DataArea();
    }

    /**
     * Create an instance of {@link RespondKPIValueType.DataArea }
     * 
     */
    public RespondKPIValueType.DataArea createRespondKPIValueTypeDataArea() {
        return new RespondKPIValueType.DataArea();
    }

    /**
     * Create an instance of {@link ChangeKPIInstanceType.DataArea }
     * 
     */
    public ChangeKPIInstanceType.DataArea createChangeKPIInstanceTypeDataArea() {
        return new ChangeKPIInstanceType.DataArea();
    }

    /**
     * Create an instance of {@link ShowKPIDefinitionType.DataArea }
     * 
     */
    public ShowKPIDefinitionType.DataArea createShowKPIDefinitionTypeDataArea() {
        return new ShowKPIDefinitionType.DataArea();
    }

    /**
     * Create an instance of {@link AcknowledgeKPIValueType.DataArea }
     * 
     */
    public AcknowledgeKPIValueType.DataArea createAcknowledgeKPIValueTypeDataArea() {
        return new AcknowledgeKPIValueType.DataArea();
    }

    /**
     * Create an instance of {@link ConfirmBODType.DataArea }
     * 
     */
    public ConfirmBODType.DataArea createConfirmBODTypeDataArea() {
        return new ConfirmBODType.DataArea();
    }

    /**
     * Create an instance of {@link RespondKPIInstanceType.DataArea }
     * 
     */
    public RespondKPIInstanceType.DataArea createRespondKPIInstanceTypeDataArea() {
        return new RespondKPIInstanceType.DataArea();
    }

    /**
     * Create an instance of {@link ProcessKPIInstanceType.DataArea }
     * 
     */
    public ProcessKPIInstanceType.DataArea createProcessKPIInstanceTypeDataArea() {
        return new ProcessKPIInstanceType.DataArea();
    }

    /**
     * Create an instance of {@link RespondKPIDefinitionType.DataArea }
     * 
     */
    public RespondKPIDefinitionType.DataArea createRespondKPIDefinitionTypeDataArea() {
        return new RespondKPIDefinitionType.DataArea();
    }

    /**
     * Create an instance of {@link ProcessKPIValueType.DataArea }
     * 
     */
    public ProcessKPIValueType.DataArea createProcessKPIValueTypeDataArea() {
        return new ProcessKPIValueType.DataArea();
    }

    /**
     * Create an instance of {@link AcknowledgeKPIDefinitionType.DataArea }
     * 
     */
    public AcknowledgeKPIDefinitionType.DataArea createAcknowledgeKPIDefinitionTypeDataArea() {
        return new AcknowledgeKPIDefinitionType.DataArea();
    }

    /**
     * Create an instance of {@link ShowKPIValueType.DataArea }
     * 
     */
    public ShowKPIValueType.DataArea createShowKPIValueTypeDataArea() {
        return new ShowKPIValueType.DataArea();
    }

    /**
     * Create an instance of {@link AcknowledgeKPIInstanceType.DataArea }
     * 
     */
    public AcknowledgeKPIInstanceType.DataArea createAcknowledgeKPIInstanceTypeDataArea() {
        return new AcknowledgeKPIInstanceType.DataArea();
    }

    /**
     * Create an instance of {@link GetKPIInstanceType.DataArea }
     * 
     */
    public GetKPIInstanceType.DataArea createGetKPIInstanceTypeDataArea() {
        return new GetKPIInstanceType.DataArea();
    }

    /**
     * Create an instance of {@link SyncKPIDefinitionType.DataArea }
     * 
     */
    public SyncKPIDefinitionType.DataArea createSyncKPIDefinitionTypeDataArea() {
        return new SyncKPIDefinitionType.DataArea();
    }

    /**
     * Create an instance of {@link SyncKPIValueType.DataArea }
     * 
     */
    public SyncKPIValueType.DataArea createSyncKPIValueTypeDataArea() {
        return new SyncKPIValueType.DataArea();
    }

    /**
     * Create an instance of {@link ProcessKPIDefinitionType.DataArea }
     * 
     */
    public ProcessKPIDefinitionType.DataArea createProcessKPIDefinitionTypeDataArea() {
        return new ProcessKPIDefinitionType.DataArea();
    }

    /**
     * Create an instance of {@link CancelKPIValueType.DataArea }
     * 
     */
    public CancelKPIValueType.DataArea createCancelKPIValueTypeDataArea() {
        return new CancelKPIValueType.DataArea();
    }

    /**
     * Create an instance of {@link ChangeKPIValueType.DataArea }
     * 
     */
    public ChangeKPIValueType.DataArea createChangeKPIValueTypeDataArea() {
        return new ChangeKPIValueType.DataArea();
    }

    /**
     * Create an instance of {@link CancelKPIInstanceType.DataArea }
     * 
     */
    public CancelKPIInstanceType.DataArea createCancelKPIInstanceTypeDataArea() {
        return new CancelKPIInstanceType.DataArea();
    }

    /**
     * Create an instance of {@link GetKPIValueType.DataArea }
     * 
     */
    public GetKPIValueType.DataArea createGetKPIValueTypeDataArea() {
        return new GetKPIValueType.DataArea();
    }

    /**
     * Create an instance of {@link CancelKPIDefinitionType.DataArea }
     * 
     */
    public CancelKPIDefinitionType.DataArea createCancelKPIDefinitionTypeDataArea() {
        return new CancelKPIDefinitionType.DataArea();
    }

    /**
     * Create an instance of {@link SyncKPIInstanceType.DataArea }
     * 
     */
    public SyncKPIInstanceType.DataArea createSyncKPIInstanceTypeDataArea() {
        return new SyncKPIInstanceType.DataArea();
    }

    /**
     * Create an instance of {@link ChangeKPIDefinitionType.DataArea }
     * 
     */
    public ChangeKPIDefinitionType.DataArea createChangeKPIDefinitionTypeDataArea() {
        return new ChangeKPIDefinitionType.DataArea();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetKPIDefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "GetKPIDefinition")
    public JAXBElement<GetKPIDefinitionType> createGetKPIDefinition(GetKPIDefinitionType value) {
        return new JAXBElement<GetKPIDefinitionType>(_GetKPIDefinition_QNAME, GetKPIDefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangeKPIInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "ChangeKPIInstance")
    public JAXBElement<ChangeKPIInstanceType> createChangeKPIInstance(ChangeKPIInstanceType value) {
        return new JAXBElement<ChangeKPIInstanceType>(_ChangeKPIInstance_QNAME, ChangeKPIInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RespondKPIValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "RespondKPIValue")
    public JAXBElement<RespondKPIValueType> createRespondKPIValue(RespondKPIValueType value) {
        return new JAXBElement<RespondKPIValueType>(_RespondKPIValue_QNAME, RespondKPIValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowKPIInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "ShowKPIInstance")
    public JAXBElement<ShowKPIInstanceType> createShowKPIInstance(ShowKPIInstanceType value) {
        return new JAXBElement<ShowKPIInstanceType>(_ShowKPIInstance_QNAME, ShowKPIInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AcknowledgeKPIValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "AcknowledgeKPIValue")
    public JAXBElement<AcknowledgeKPIValueType> createAcknowledgeKPIValue(AcknowledgeKPIValueType value) {
        return new JAXBElement<AcknowledgeKPIValueType>(_AcknowledgeKPIValue_QNAME, AcknowledgeKPIValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowKPIDefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "ShowKPIDefinition")
    public JAXBElement<ShowKPIDefinitionType> createShowKPIDefinition(ShowKPIDefinitionType value) {
        return new JAXBElement<ShowKPIDefinitionType>(_ShowKPIDefinition_QNAME, ShowKPIDefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfirmBODType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "ConfirmBOD")
    public JAXBElement<ConfirmBODType> createConfirmBOD(ConfirmBODType value) {
        return new JAXBElement<ConfirmBODType>(_ConfirmBOD_QNAME, ConfirmBODType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessKPIInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "ProcessKPIInstance")
    public JAXBElement<ProcessKPIInstanceType> createProcessKPIInstance(ProcessKPIInstanceType value) {
        return new JAXBElement<ProcessKPIInstanceType>(_ProcessKPIInstance_QNAME, ProcessKPIInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RespondKPIInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "RespondKPIInstance")
    public JAXBElement<RespondKPIInstanceType> createRespondKPIInstance(RespondKPIInstanceType value) {
        return new JAXBElement<RespondKPIInstanceType>(_RespondKPIInstance_QNAME, RespondKPIInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KPIValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "KPIValue")
    public JAXBElement<KPIValueType> createKPIValue(KPIValueType value) {
        return new JAXBElement<KPIValueType>(_KPIValue_QNAME, KPIValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessKPIValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "ProcessKPIValue")
    public JAXBElement<ProcessKPIValueType> createProcessKPIValue(ProcessKPIValueType value) {
        return new JAXBElement<ProcessKPIValueType>(_ProcessKPIValue_QNAME, ProcessKPIValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RespondKPIDefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "RespondKPIDefinition")
    public JAXBElement<RespondKPIDefinitionType> createRespondKPIDefinition(RespondKPIDefinitionType value) {
        return new JAXBElement<RespondKPIDefinitionType>(_RespondKPIDefinition_QNAME, RespondKPIDefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AcknowledgeKPIDefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "AcknowledgeKPIDefinition")
    public JAXBElement<AcknowledgeKPIDefinitionType> createAcknowledgeKPIDefinition(AcknowledgeKPIDefinitionType value) {
        return new JAXBElement<AcknowledgeKPIDefinitionType>(_AcknowledgeKPIDefinition_QNAME, AcknowledgeKPIDefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowKPIValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "ShowKPIValue")
    public JAXBElement<ShowKPIValueType> createShowKPIValue(ShowKPIValueType value) {
        return new JAXBElement<ShowKPIValueType>(_ShowKPIValue_QNAME, ShowKPIValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AcknowledgeKPIInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "AcknowledgeKPIInstance")
    public JAXBElement<AcknowledgeKPIInstanceType> createAcknowledgeKPIInstance(AcknowledgeKPIInstanceType value) {
        return new JAXBElement<AcknowledgeKPIInstanceType>(_AcknowledgeKPIInstance_QNAME, AcknowledgeKPIInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetKPIInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "GetKPIInstance")
    public JAXBElement<GetKPIInstanceType> createGetKPIInstance(GetKPIInstanceType value) {
        return new JAXBElement<GetKPIInstanceType>(_GetKPIInstance_QNAME, GetKPIInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SyncKPIDefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "SyncKPIDefinition")
    public JAXBElement<SyncKPIDefinitionType> createSyncKPIDefinition(SyncKPIDefinitionType value) {
        return new JAXBElement<SyncKPIDefinitionType>(_SyncKPIDefinition_QNAME, SyncKPIDefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SyncKPIValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "SyncKPIValue")
    public JAXBElement<SyncKPIValueType> createSyncKPIValue(SyncKPIValueType value) {
        return new JAXBElement<SyncKPIValueType>(_SyncKPIValue_QNAME, SyncKPIValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelKPIValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "CancelKPIValue")
    public JAXBElement<CancelKPIValueType> createCancelKPIValue(CancelKPIValueType value) {
        return new JAXBElement<CancelKPIValueType>(_CancelKPIValue_QNAME, CancelKPIValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessKPIDefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "ProcessKPIDefinition")
    public JAXBElement<ProcessKPIDefinitionType> createProcessKPIDefinition(ProcessKPIDefinitionType value) {
        return new JAXBElement<ProcessKPIDefinitionType>(_ProcessKPIDefinition_QNAME, ProcessKPIDefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangeKPIValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "ChangeKPIValue")
    public JAXBElement<ChangeKPIValueType> createChangeKPIValue(ChangeKPIValueType value) {
        return new JAXBElement<ChangeKPIValueType>(_ChangeKPIValue_QNAME, ChangeKPIValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KPIInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "KPIInstance")
    public JAXBElement<KPIInstanceType> createKPIInstance(KPIInstanceType value) {
        return new JAXBElement<KPIInstanceType>(_KPIInstance_QNAME, KPIInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KPIDefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "KPIDefinition")
    public JAXBElement<KPIDefinitionType> createKPIDefinition(KPIDefinitionType value) {
        return new JAXBElement<KPIDefinitionType>(_KPIDefinition_QNAME, KPIDefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetKPIValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "GetKPIValue")
    public JAXBElement<GetKPIValueType> createGetKPIValue(GetKPIValueType value) {
        return new JAXBElement<GetKPIValueType>(_GetKPIValue_QNAME, GetKPIValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelKPIInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "CancelKPIInstance")
    public JAXBElement<CancelKPIInstanceType> createCancelKPIInstance(CancelKPIInstanceType value) {
        return new JAXBElement<CancelKPIInstanceType>(_CancelKPIInstance_QNAME, CancelKPIInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelKPIDefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "CancelKPIDefinition")
    public JAXBElement<CancelKPIDefinitionType> createCancelKPIDefinition(CancelKPIDefinitionType value) {
        return new JAXBElement<CancelKPIDefinitionType>(_CancelKPIDefinition_QNAME, CancelKPIDefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangeKPIDefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "ChangeKPIDefinition")
    public JAXBElement<ChangeKPIDefinitionType> createChangeKPIDefinition(ChangeKPIDefinitionType value) {
        return new JAXBElement<ChangeKPIDefinitionType>(_ChangeKPIDefinition_QNAME, ChangeKPIDefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SyncKPIInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mesa.org/xml/KPI-ML-V01", name = "SyncKPIInstance")
    public JAXBElement<SyncKPIInstanceType> createSyncKPIInstance(SyncKPIInstanceType value) {
        return new JAXBElement<SyncKPIInstanceType>(_SyncKPIInstance_QNAME, SyncKPIInstanceType.class, null, value);
    }

}
